# Form implementation generated from reading ui file 'selected_gadgetDetails_.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.ROPChain = QtWidgets.QWidget()
        self.ROPChain.setObjectName("ROPChain")
        self.GadgetDetailsTabs.addTab(self.ROPChain, "")
        self.verticalLayout_2.addWidget(self.GadgetDetailsTabs)
        self.verticalLayout.addWidget(self.GadgetDetails_Frame)
        self.verticalLayout_4.addWidget(self.Right_Frame)
        MainWindow.setCentralWidget(self.Central_Widget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 19))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_file = QtGui.QAction(parent=MainWindow)
        self.actionLoad_file.setObjectName("actionLoad_file")
        self.actionRemove_file = QtGui.QAction(parent=MainWindow)
        self.actionRemove_file.setObjectName("actionRemove_file")
        self.menuMenu.addAction(self.actionLoad_file)
        self.menuMenu.addAction(self.actionRemove_file)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.GadgetDetailsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #self.offset_keyword.setText(_translate("MainWindow", "Offset:"))
        #self.offset_value.setText(_translate("MainWindow", "0x123456"))
        #self.modified_registers_keyword.setText(_translate("MainWindow", "Modified Registers:"))
        #self.modified_registers.setText(_translate("MainWindow", "R8, R12, 123, 123, 123, 123"))
        #self.stack_size.setText(_translate("MainWindow", "Stack Size:"))
        #self.stack_size_2.setText(_translate("MainWindow", "24"))
#         self.assembly_code.setText(_translate("MainWindow", "mov    edx,len     ;message length\n"
# "   mov    ecx,msg     ;message to write\n"
# "   mov    ebx,1       ;file descriptor (stdout)\n"
# "   mov    eax,4       ;system call number (sys_write)\n"
# "   int    0x80        ;call kernel"))
        #self.GadgetDetailsTabs.setTabText(self.GadgetDetailsTabs.indexOf(self.SelectedGadgetDetails), _translate("MainWindow", "Selected Gadget Details"))
        #self.GadgetDetailsTabs.setTabText(self.GadgetDetailsTabs.indexOf(self.ROPChain), _translate("MainWindow", "ROP Chain"))
        self.menuMenu.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_file.setText(_translate("MainWindow", "Load"))
        self.actionRemove_file.setText(_translate("MainWindow", "Remove"))
